### ISSUE TITLE
Lightweight transaction when updating fields

### ISSUE THREAD

**Issue by RileyJia** [spring-projects/spring-data-cassandra#1122]
Hi, I am fairly new to use this library and have a question about implementing the lightweight transaction. I am trying to update one field in a row only when this row is already existed. What I've found so far is something like this command:
```cassandraTemplate.update(Query.query(where("id").is(id)), Update.empty().addTo("addresses").append(address)), Person.class);```
But it will add new rows for new entries.

I saw in the document, the lightweight transaction is supported in this function:
`WriteResult update (Object objectToSave, UpdateOptions options)`
But that means I have to update the whole object which right now, for some reason, I don't have access to.

So is there a way to use the lightweight transactions in the first command, or is there something else I could use to implement the same function as this CQL command by using `CassandraTemplate`: 
`UPDATE person SET addresses = addresses + :address WHERE id = :id IF EXISTS`

Thanks

**Comment by mp911de** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it).

You can attach `UpdateOptions` to `Query` via:

```java
Query query = Query.query(where("id").is(id))
		.queryOptions(UpdateOptions.builder().withIfExists().build());
```

See also the test for [`StatementFactory`](https://github.com/spring-projects/spring-data-cassandra/blob/692b51bd6d88742a5d879a9d023093ca553e8b76/spring-data-cassandra/src/test/java/org/springframework/data/cassandra/core/StatementFactoryUnitTests.java#L495-L502).
