### ISSUE TITLE
Updating from 3.1.9 to 3.2.0 breaks annotation detection (e.g. @Column) on properties defined in Kotlin primary constructor

### ISSUE THREAD

**Issue by bzikarsky** [spring-projects/spring-data-cassandra#1136]
# Description

The following "entity" correctly maps `bar` to column `foo` with spring-data-cassandra `3.1.9`. Using
`3.2.0` (or `3.2.1`) generates incorrect CQL statements with a reference to the undefined column `bar`:

```kotlin
class Example(
    @PrimaryKey val id: Long,
    @Column("foo") val bar: Long
)
```

**Error**: 

    Query; CQL [INSERT INTO example (bar,id) VALUES (?,?)]; Undefined column name bar; nested exception is com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Undefined column name bar

It is important to note though that `@PrimaryKey` does not suffer from a similar problem. Mapping inline properties
to different columns via values in `@PrimaryKey` works as expected.

The triage started in [a StackOverflow thread](https://stackoverflow.com/questions/67673888/column-cassandra-annotation-ignored-with-spring-boot-2-5-0-works-with-2-4-6). This thread also provides a minimum working example which is a good start to reproduce this issue.

# Analysis

We tried a few things during triage.

## Set `forceQuote = true` in `@Column`

We wanted to see whether `forceQuote` gives us additional quotes around `bar`. By this, we wanted to see whether the 
annotation is used at all. 

**Additional quotes did not show up, we assume that the annotation is completely ignored**.

## Use "normal" properties instead of inlined properties  as part of the primary ctor

```kotlin
class Example(id: Long, bar: Long) {
    @PrimaryKey val id = id
    @Column("foo") val bar = bar
}
```

**This works as expected.**

## Force annotations to the Kotlin get-semantics via `@get: <Annotation>`

```kotlin
class Example(
    @PrimaryKey
    val id: Long,

    @get: Column("foo")
    val bar: Long
)
```

**This also works as expected.**

# Conclusion

It looks like that a change for `3.2.0` broke something in the handling/detection of annotations related to constructor arguments.
Possibly this bug was introduced as part (or in the context) of [`Consider @column and @element annotated constructor parameters.`](https://github.com/spring-projects/spring-data-cassandra/commit/f75d692221d04e5bfb7dbd24eeb5e7481a419b03)

**Comment by mp911de** [comment]
Duplicated by #1146

[Kotlin has its own opinion on annotation targets](https://kotlinlang.org/docs/annotations.html#annotation-use-site-targets) when an annotation allows multiple usages in exchange for concise notation of classes and data class components.

From a Java perspective, this change was an improvement but breaks Kotlin code and we have no means to make things work in Java compilers while not breaking functionality for Kotlin users. The only way out would be a new annotation and that would introduce ambiguity within our codebase which approach to use.

If you run into these issues we recommend creating a meta-annotation (as `@Column` can be used on annotations) in combination with `@AliasFor` within your project to specifically direct annotations towards fields instead of unintentional constructor argument annotations.

**Comment by Dobiasd** [comment]
Replacing

```kotlin
    PrimaryKey val id: Long,
    Column("foo") val bar: Long
```

with

```kotlin
    @field:PrimaryKey val id: Long,
    @field:Column("foo") val bar: Long
```

works perfectly.

Thanks a lot!
