### ISSUE TITLE
CassandraTemplate shouldn't be initialized with the usage of prepared statements enabled by default

### ISSUE THREAD

**Issue by mariusneo** [spring-projects/spring-data-cassandra#1138]
While doing the developments for #677  , by default the CassandraTemplate will be using prepared statements to interact with Cassandra.

Executing a simple statement via:

```
         final SimpleStatement select = QueryBuilder.selectFrom(tableName).all()
                .where(relations)
                .build()
                .setConsistencyLevel(ConsistencyLevel.LOCAL_QUORUM);

        return cassandraOperations.select(select, AdCountByAdByUser.class);
```

will issue in the background the creation of a prepared statement.
Now, if the code querying Cassandra doesn't make use of prepared statements, but instead of simple statements, they will still land in Cassandra as prepared statements.

As a consequence, the table `system.prepared_statements` is going to get quite big ( > 1 GB) in productive systems:

```
select * from system.prepared_statements ;
```

As a consequence, restarting a Cassandra node may take a while.

I'd actually expect that the usage of prepared statements in CassandraTemplate to be disabled by default and leave this choice to the client.

**Comment by mp911de** [comment]
During the development of prepared statement support, we initially defaulted to simple statements. After getting in touch with Datastax, the Datastax team recommended enabling prepared statements by default to generally improve performance. 

Paging @adutra @clun

**Comment by mariusneo** [comment]
```
SELECT * FROM my_table WHERE user_id=6e578dee-746a-4700-b750-b34e9d305250 and event_type in (1,2,3)
```

The simple statement is created via a code similar to the one posted in my previous comment.


My expectation as a user is that i will be dealing with a simple statement, but by using spring data casssandra with the default configuration, I am executing now behind the scenes a prepared statement and get a corresponding entry within `system.prepared_statements`.
IMO using prepared statements should be something made explicit by the user and not implicitly.

https://docs.datastax.com/en/developer/java-driver/4.11/manual/core/statements/prepared/

**Comment by mp911de** [comment]
I'm not sure whether there's a possibility to issue simple statements directly if they do not contain placeholders or whether it actually makes sense. Maybe there's an opportunity to optimize for cases where simple statements are sufficient to avoid filling up system tables.

**Comment by mariusneo** [comment]
I think that it is not quite possible within spring data cassandra to say whether a statement should be prepared or not.
In some cases when dealing with non-parameterized common statements it may make sense, in most cases however it doesn't make sense.
This detail (whether to use prepared statements or not) should be left to the client building the statement provided to the CassandraOperations concrete instance.

**Comment by mp911de** [comment]
> This detail (whether to use prepared statements or not) should be left to the client building the statement provided to the CassandraOperations concrete instance.

That's not going to work because we have to have a default. `CassandraOperations` operates primarily at the granularity of entity operations by generating CQL itself for `INSERT`/`UPDATE`/… with the option to accept `Statement` objects created from repository query methods. We cannot distinguish whether a statement originates from a repository query method or whether the application code calls `CassandraOperations`.

Any custom `CQL` statements can be run through `CqlOperations` if you want to generally bypass prepared statement usage. 

I see two options here:

1. You can configure your own `CassandraTemplate` bean
2. You can disable prepared statement support by registering a `BeanPostProcessor` if you want to keep Spring's defaults

If you're a Spring Boot user, you could ask Spring Boot to introduce a configuration flag to enable/disable prepared statement usage for easier override.

**Comment by adutra** [comment]
Hi, sorry for the late response.

We at DataStax can confirm that the general recommendation is to use prepared statements for efficiency. Server-side, you save the burden of parsing the CQL query every time; and driver-side, most drivers are able to cache prepared statements in order to avoid preparing multiple types the same query.

There are only a few good use cases for simple statements, e.g. a one-shot query that the application executes only once at startup. For these use cases, as @mp911de rightfully reminded, it is fair to recommend using `CqlOperations`.

For all other cases, the general recommendation is to prepare a handful of (parameterized) statements at application startup, then execute only bound statements (with different bound values for each instance) during the application lifetime.

I recommend reading our [docs on prepared statements](https://docs.datastax.com/en/developer/java-driver/4.12/manual/core/statements/prepared/).

**Comment by mp911de** [comment]
Thanks a lot. Since we're in line with recommendations and there isn't anything actionable left for now, I'll close the ticket.
