### ISSUE TITLE
Adopt CqlSession::executeReactive  

### ISSUE THREAD

**Issue by samueldlightfoot** [spring-projects/spring-data-cassandra#1242]
The core DataStax driver now exposes an executeReactive method in CqlSession that returns their own ReactiveResultSet. I believe this used to be DSE only, but has recently moved into the core module.

Raising this ticket to open the question as to whether it is worth moving to consume the (new) reactive counterparts to CqlSession.

**Comment by mp911de** [comment]
This isn't going to happen. The reason is the execution model design of `ReactiveSession`. The returned `ReactiveResultSet` is a `Publisher<Row>` that defines access to additional publishers such as `Publisher<? extends ColumnDefinitions> getColumnDefinitions()` or `Publisher<Boolean> wasApplied()`. Accessing those details requires additional publisher materialization and transformation. 

It isn't compatible with our `ReactiveResultSet` model where an execution returns a `Publisher<ReactiveResultSet>` that holds already the first page of results including `wasApplied`/`ExecutionInfo` for the first execution.

We discussed the design with the DataStax team but at that time, the design was already released and it wasn't possible to revise an already released public API.
