### ISSUE TITLE
Column name is ignored when @Id is used

### ISSUE THREAD

**Issue by mkubele** [spring-projects/spring-data-cassandra#1296]
It seems that column name is ignored when @Id annotation is used in Kotlin
I have this table:
```
@Table("customer")
data class Customer(
    @field:Id
    @field:PrimaryKeyColumn(name = "first_name", type = PrimaryKeyType.PARTITIONED)
    val firstName: String,
    @field:Column("last_name")
    val lastName: String
)
```
and when I want to use the default _findById()_ function, it fails because of unknown column
>org.springframework.data.cassandra.CassandraInvalidQueryException: ReactivePreparedStatementCallback; CQL [SELECT * FROM customer WHERE firstname=? LIMIT 1]; Undefined column name firstname; nested exception is com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Undefined column name firstname

**Comment by mp911de** [comment]
`@Id` and `@PrimaryKeyColumn` overlap to some extent. `@Id` is an annotation of Spring Data Commons that doesn't contain any store-specifics while `@PrimaryKeyColumn` is typically used for composite primary keys.

Please replace both annotations with a single `@PrimaryKey` annotation that allows you to specify the column name. Since you have a single primary key column, the key type is always `PARTITIONED`.
