### ISSUE TITLE
Crac Support - Lifecycle Implementation

### ISSUE THREAD

**Issue by michaelmcfadyensky** [spring-projects/spring-data-cassandra#1486]
To be able to use Crac with spring boot applications, all open connections need to be closed before a checkpoint is taken and then they need to be re-established after a checkpoint is restored. 

Spring framework has added in support for automatically stopping any implementations of `Lifecycle` before the checkpoint and starting them after the checkpoint restore. (https://github.com/spring-projects/spring-framework/issues/29921)

There has been several issues/PRs raised to provide support for this for kafka, web servers, redis, jdbc etc (https://github.com/spring-projects/spring-kafka/issues/2760) however there is currently no support for cassandra.

Currently, if you attempt to take a checkpoint of a spring cassandra app, it will result in the following error.

```
jdk.internal.crac.CheckpointException
        at java.base/jdk.internal.crac.Core.checkpointRestore1(Core.java:122)
        at java.base/jdk.internal.crac.Core.checkpointRestore(Core.java:246)
        at java.base/jdk.internal.crac.Core.checkpointRestoreInternal(Core.java:262)
        Suppressed: jdk.internal.crac.impl.CheckpointOpenSocketException: tcp localAddr 172.17.0.3 localPort 52866 remoteAddr 172.17.0.5 remotePort 9042
                at java.base/jdk.internal.crac.Core.translateJVMExceptions(Core.java:91)
                at java.base/jdk.internal.crac.Core.checkpointRestore1(Core.java:145)
                ... 2 more
```
(i've condensed the full error log as its very long)

**Requirements**
- To be able to use Crac in a spring boot app with the spring data cassandra starter

**Comment by christophstrobl** [comment]
Thank you for reaching out. The cassandra driver tries to connect to the db early which opens the socket. Changes contained in #1485 and proposed via spring-projects/spring-boot#39948 allow to defer the actual connect, which in turn may allow to create a checkpoint as long as no interaction with the database happens. 
At the moment there's no out of the box solution that allows to capture an in flight snapshot with the `CqlSession` being initialized. You may want to give the spring-cloud [`@RefreshScope`](https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/application-context-services.html#refresh-scope) a try.

**Comment by mp911de** [comment]
Spring Data Cassandra's infrastructure support is comprised of `FactoryBean`s that expect eager initialization as lifecycle processing happens after the factory is expected to return its bean object. The other aspect is that `CqlSession` is an object that is created and destroyed after usage. `CqlSession` doesn't expose any lifecycle methods. After destroying the object, it is no longer functional and references to this object need to be discarded in order to obtain a new, connected instance.

We do not plan on adding further utilities in Spring Data Cassandra to widen Checkpoint-Restore arrangements. Any kind of support would have to reside in Spring Boot as Boot's Cassandra support doesn't require Spring Data.
